# Generated by Django 3.2.7 on 2021-10-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0002_users_user_type'),
        ('manager', '0004_alter_fooditems_description'),
        ('cashier', '0002_auto_20211020_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ItemQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fooditems')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rating_for_food', models.FloatField()),
                ('message', models.CharField(max_length=255)),
                ('by', models.ForeignKey(limit_choices_to={'user_type': 'Customer'}, on_delete=django.db.models.deletion.DO_NOTHING, to='access.users')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cashier.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.FloatField(default=0)),
                ('last_date_of_add', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(limit_choices_to={'user_type': 'Customer'}, on_delete=django.db.models.deletion.CASCADE, to='access.users')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='customer.ItemQuantity', to='manager.FoodItems'),
        ),
        migrations.AddField(
            model_name='cart',
            name='offer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.everydayoffers'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Customer'}, on_delete=django.db.models.deletion.CASCADE, to='access.users'),
        ),
    ]
