# Generated by Django 3.2.7 on 2021-10-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0002_users_user_type'),
        ('cashier', '0002_auto_20211020_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rating_for_food', models.FloatField()),
                ('message', models.CharField(max_length=255)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='access.users')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cashier.orders')),
            ],
        ),
    ]
