# Generated by Django 3.2.7 on 2021-10-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_users_user_type'),
        ('manager', '0004_alter_fooditems_description'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.FloatField(default=0)),
                ('last_date_of_add', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(limit_choices_to={'user_type': 'Customer'}, on_delete=django.db.models.deletion.CASCADE, to='access.users')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='manager.FoodItems')),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.everydayoffers')),
                ('user_id', models.ForeignKey(limit_choices_to={'user_type': 'Customer'}, on_delete=django.db.models.deletion.CASCADE, to='access.users')),
            ],
        ),
    ]
