# Generated by Django 3.2.7 on 2021-10-24 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_fooditems_description'),
        ('customer', '0002_alter_cart_offer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.fooditems'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemQuantity',
        ),
    ]
