# Generated by Django 3.2.7 on 2021-10-25 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
        ('customer', '0002_feedback_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.orders'),
        ),
    ]
