# Generated by Django 3.2.7 on 2021-10-25 07:09

import customer.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_users_user_type'),
        ('customer', '0003_alter_feedback_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'Customer'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='access.users'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_id',
            field=models.CharField(auto_created=True, default=customer.models.unique_key_generator, max_length=10, primary_key=True, serialize=False),
        ),
    ]
