# Generated by Django 3.2.7 on 2021-10-25 05:29

import cashier.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0005_alter_fooditems_name'),
        ('access', '0002_users_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('rating', models.FloatField(default=5.0)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.fooditems')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.CharField(auto_created=True, default=cashier.models.unique_key_generator, max_length=10, primary_key=True, serialize=False)),
                ('total_cost', models.FloatField(default=0)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(through='cashier.ItemQuantity', to='manager.FoodItems')),
                ('user_id', models.ForeignKey(limit_choices_to={'user_type': 'Customer'}, on_delete=django.db.models.deletion.CASCADE, to='access.users')),
            ],
        ),
        migrations.AddField(
            model_name='itemquantity',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cashier.orders'),
        ),
    ]
