# Generated by Django 3.2.7 on 2021-10-25 05:38

import cashier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(auto_created=True, default=cashier.models.unique_key_generator, max_length=10, unique=True),
        ),
    ]
