# Generated by Django 3.2.7 on 2021-10-20 16:03

import cashier.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_everydayoffers'),
        ('access', '0002_users_user_type'),
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=cashier.models.unique_key_generator, max_length=10, unique=True)),
                ('total_cost', models.FloatField()),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(to='manager.FoodItems')),
                ('user_id', models.ForeignKey(limit_choices_to={'user_type': 'Customer'}, on_delete=django.db.models.deletion.CASCADE, to='access.users')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderCoupons',
        ),
    ]
