# Generated by Django 3.2.7 on 2021-10-24 11:48

import cashier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_auto_20211020_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(auto_created=True, default=cashier.models.unique_key_generator, max_length=10, unique=True),
        ),
    ]
