# Generated by Django 3.2.7 on 2021-10-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_fooditems_name'),
        ('cashier', '0003_alter_orders_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.fooditems')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cashier.orders')),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='items',
        ),
        migrations.AddField(
            model_name='orders',
            name='items',
            field=models.ManyToManyField(through='cashier.ItemQuantity', to='manager.FoodItems'),
        )
    ]
