# Generated by Django 3.2.7 on 2021-09-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('mobile_no', models.IntegerField(unique=True)),
            ],
        ),
    ]
