# Generated by Django 3.2.7 on 2021-09-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Cashier', 'Cashier'), ('Manager', 'Manager')], default='Customer', max_length=9),
        ),
    ]
