# Generated by Django 3.2.7 on 2021-10-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_everydayoffers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='description',
            field=models.CharField(max_length=160),
        ),
    ]
