# Generated by Django 3.2.7 on 2021-10-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_fooditems_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
